name: Deploy to GitHub Pages

on:
  push:
    branches: [test, main]
    paths:
      - 'docs/**'

jobs:
  deploy:
    if: github.repository_owner == 'newbietan'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    steps:
      - uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: 'docs'

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4